Testcase
pymontecarlo/pymontecarlo pull request #67
Opened 2018-09-30 17:11 UTC by luoc0815

I modified the test case a little in order to simplify my tests in pymontecarlo-reconstruction.

2018-09-30 18:52 UTC, ppinard requested changes
Everything else looks good

2018-09-30 18:52 UTC, ppinard commented on pymontecarlo/testcase.py
> +        results.append(self.create_basic_kratioresult())
Why do you add two KRatioResult?

2018-09-30 18:53 UTC, ppinard commented
Could you also fix the broken tests?

2018-10-01 07:20 UTC, 0b11001111 commented on pymontecarlo/testcase.py
> +        results.append(self.create_basic_kratioresult())
This is what I've observed in real samples - two k-ratio results in one simulation. I was wondering too if that makes sense. However, it won't affect my code if one is removed.

2019-01-20 16:18 UTC, ppinard approved these changes

2019-01-20 16:18 UTC, merged